### PR TITLE
Update to 0.9.36

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
Hmm, it looks like that buildbot has some issues with this PR or I don't have rights to trigger the build on this PR. @TingPing Any idea?

**Comment by bilelmoussaoui** [comment]
bot, build

**Comment by TingPing** [comment]
@AsciiWolf Only the maintainer of a package can trigger the bot.

**Comment by AsciiWolf** [comment]
Build [succeeded](https://flathub.org/builds/#/builders/2/builds/4531).

**Pull request merged**
