### PR TITLE
Fix Firefox sync 

### LINKED ISSUE #13: Syncing with Firefox is not working
When I try to connect to my Firefox account it says the syncing is not working because there is no module called 'cryptography'.

### PR DESCRIPTION
**Pull request by qnixsynapse**
Fixes #13 .

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@sesivany mind testing this if it does works for you?

**Comment by ghost** [comment]
The test build is gone, can we get a fresh build to test with please?

**Comment by qnixsynapse** [comment]
@measlytwerp  There is a new version. I will update it into this one and then you can test.

**Comment by qnixsynapse** [comment]
Whoops! I messed up the commit message :(

**Comment by ghost** [comment]
Thanks @biswasab!

The crash experienced when typing in the URL bar has gone, however Sync still failed, I've attached a log of everything that was out.

I was able to set up Sync with GNOME Web at the same time with the same credentials.

[eolie.log](https://github.com/flathub/org.gnome.Eolie/files/3145265/eolie.log)

**Comment by qnixsynapse** [comment]
@measlytwerp I think this error should be reported upstream.

```
Sign in with this email type is not currently supported
```

**Comment by ghost** [comment]
I should say, that came from my first attempt where I probably typed something incorrectly, the correctly filled out the form and submitting it three times gave:

```Incorrect email case```

**Comment by qnixsynapse** [comment]
Working fine here. Remember you need a firefox account to sync first

Screenshot from 2019-05-05 13-40-57

**Comment by ghost** [comment]
Yep, I used my Firefox account, it Synced fine in Web, there's this upstream issue:

https://gitlab.gnome.org/World/eolie/issues/336

**Comment by qnixsynapse** [comment]
@measlytwerp  Yup. The problem on the flatpak side was the python3 module called cryptography was failing to build for some reason. I have fixed that in this PR.

**Comment by bilelmoussaoui** [comment]
Fixed by https://github.com/flathub/org.gnome.Eolie/pull/25

**Pull request closed without merging**
